[package]
name = "messycanvasctl"
version = "0.0.0-dev.0"
authors = ["Kaede Hoshikawa <futursolo@icloud.com>"]
description = "Command line tool for messycanvas"
license = "Apache-2.0"

[[bin]]
name = "canvasctl"
path = "src/main.rs"

[dependencies]
